### ISSUE TITLE
Add `getStream` to interfaces.

### ISSUE THREAD

**Issue by Metalaka** [hoaproject/Stream#16]
Since #15 `Hoa\Stream::getStream` is public.

But because interfaces is commonly used in type hinting, this method can't be used safely.
eg: `class Foo extends Hoa\Stream\IStream\In { …` which doesn't implement `getStream`.

IMO this method should be present in all `Hoa\Stream\IStream` interfaces.

Related to https://github.com/hoaproject/Console/pull/51

**Comment by Hywan** [comment]
Hello :-),

I agree… So far, we assume every object of kind `Hoa\Stream\IStream\*` is also of kind `Hoa\Stream`. Does it make sense?

But this is a weak assumption. We can introduce a `Hoa\Stream\IStream\Stream` interface, that will be implemented by `Hoa\Stream` and maybe `Hoa\Stream\IStream\*` interfaces.

This will introduce a BC break. We should do that in the same time we bump the PHP version.

Thoughts?

**Comment by Metalaka** [comment]
`Hoa\Stream\IStream\Stream` must be implemented in `Hoa\Stream\IStream\*` to solve this issue.

Add an interface just for `Hoa\Stream\Stream` don't make sense.

Does it exist an issue for the next bump PHP version ?

**Comment by Hywan** [comment]
Note: It's not a BC break because the library is still in beta. So it's fine.

Yup, you're right. That's what I was meaning.

**Comment by Hywan** [comment]
So let's go :-).

And nop, no issue for the PHP5.4 drop.
